---
- name: "Install python {{ version }}"
  command: "/usr/local/pythonz/bin/pythonz install {{ version }}"
  args:
    creates: "/usr/local/pythonz/pythons/CPython-{{ version }}/bin/python"

- name: "Install virtualenv for python {{ version }}"
  pip:
    executable: "/usr/local/pythonz/pythons/CPython-{{ version }}/bin/pip3"
    name: virtualenv
    state: latest
