---
- name: "Install python {{ python_version }}"
  command: "/usr/local/pythonz/bin/pythonz install {{ python_version }}"
  args:
    creates: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/python"

- name: "Update pip & setuptools for python {{ python_version }}"
  pip:
    executable: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/pip3"
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: "{{ item.state }}"
  with_items:
    - {name: pip, state: "{{ 'present' if pip_version is defined else 'latest' }}", version: "{{ pip_version | default(omit) }}"}
    - {name: setuptools, state: "{{ 'present' if setuptools_version is defined else 'latest' }}", version: "{{ setuptools_version | default(omit) }}"}
